# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui\RunningDialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RunningDialog(object):
    def setupUi(self, RunningDialog):
        RunningDialog.setObjectName("RunningDialog")
        RunningDialog.resize(1532, 858)
        self.verticalLayout = QtWidgets.QVBoxLayout(RunningDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.myQtPlotContainer_left = MyQtPlotContainer(RunningDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.myQtPlotContainer_left.sizePolicy().hasHeightForWidth())
        self.myQtPlotContainer_left.setSizePolicy(sizePolicy)
        self.myQtPlotContainer_left.setMinimumSize(QtCore.QSize(600, 700))
        self.myQtPlotContainer_left.setMaximumSize(QtCore.QSize(600, 700))
        self.myQtPlotContainer_left.setObjectName("myQtPlotContainer_left")
        self.horizontalLayout.addWidget(self.myQtPlotContainer_left)
        self.myQtPlotContainer_right = MyQtPlotContainer(RunningDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.myQtPlotContainer_right.sizePolicy().hasHeightForWidth())
        self.myQtPlotContainer_right.setSizePolicy(sizePolicy)
        self.myQtPlotContainer_right.setMinimumSize(QtCore.QSize(600, 700))
        self.myQtPlotContainer_right.setMaximumSize(QtCore.QSize(600, 700))
        self.myQtPlotContainer_right.setObjectName("myQtPlotContainer_right")
        self.horizontalLayout.addWidget(self.myQtPlotContainer_right)
        self.plainTextEdit_messages = QtWidgets.QPlainTextEdit(RunningDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_messages.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_messages.setSizePolicy(sizePolicy)
        self.plainTextEdit_messages.setMinimumSize(QtCore.QSize(300, 700))
        self.plainTextEdit_messages.setMaximumSize(QtCore.QSize(300, 700))
        self.plainTextEdit_messages.setObjectName("plainTextEdit_messages")
        self.horizontalLayout.addWidget(self.plainTextEdit_messages)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_loadTime = QtWidgets.QLabel(RunningDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_loadTime.sizePolicy().hasHeightForWidth())
        self.label_loadTime.setSizePolicy(sizePolicy)
        self.label_loadTime.setMinimumSize(QtCore.QSize(0, 25))
        self.label_loadTime.setStyleSheet("border-color: rgb(255, 255, 0);")
        self.label_loadTime.setFrameShape(QtWidgets.QFrame.Box)
        self.label_loadTime.setText("")
        self.label_loadTime.setObjectName("label_loadTime")
        self.gridLayout.addWidget(self.label_loadTime, 0, 0, 1, 1)
        self.label_normalizeTime = QtWidgets.QLabel(RunningDialog)
        self.label_normalizeTime.setFrameShape(QtWidgets.QFrame.Box)
        self.label_normalizeTime.setText("")
        self.label_normalizeTime.setObjectName("label_normalizeTime")
        self.gridLayout.addWidget(self.label_normalizeTime, 0, 1, 1, 1)
        self.label_initTime = QtWidgets.QLabel(RunningDialog)
        self.label_initTime.setFrameShape(QtWidgets.QFrame.Box)
        self.label_initTime.setText("")
        self.label_initTime.setObjectName("label_initTime")
        self.gridLayout.addWidget(self.label_initTime, 0, 2, 1, 1)
        self.label_stepTime = QtWidgets.QLabel(RunningDialog)
        self.label_stepTime.setFrameShape(QtWidgets.QFrame.Box)
        self.label_stepTime.setText("")
        self.label_stepTime.setObjectName("label_stepTime")
        self.gridLayout.addWidget(self.label_stepTime, 0, 3, 1, 1)
        self.label_runToEndTime = QtWidgets.QLabel(RunningDialog)
        self.label_runToEndTime.setFrameShape(QtWidgets.QFrame.Box)
        self.label_runToEndTime.setText("")
        self.label_runToEndTime.setObjectName("label_runToEndTime")
        self.gridLayout.addWidget(self.label_runToEndTime, 0, 5, 1, 1)
        self.label_testTime = QtWidgets.QLabel(RunningDialog)
        self.label_testTime.setFrameShape(QtWidgets.QFrame.Box)
        self.label_testTime.setText("")
        self.label_testTime.setObjectName("label_testTime")
        self.gridLayout.addWidget(self.label_testTime, 0, 6, 1, 1)
        self.pushButton_load = QtWidgets.QPushButton(RunningDialog)
        self.pushButton_load.setObjectName("pushButton_load")
        self.gridLayout.addWidget(self.pushButton_load, 1, 0, 1, 1)
        self.pushButton_normalize = QtWidgets.QPushButton(RunningDialog)
        self.pushButton_normalize.setObjectName("pushButton_normalize")
        self.gridLayout.addWidget(self.pushButton_normalize, 1, 1, 1, 1)
        self.pushButton_init = QtWidgets.QPushButton(RunningDialog)
        self.pushButton_init.setObjectName("pushButton_init")
        self.gridLayout.addWidget(self.pushButton_init, 1, 2, 1, 1)
        self.pushButton_step = QtWidgets.QPushButton(RunningDialog)
        self.pushButton_step.setObjectName("pushButton_step")
        self.gridLayout.addWidget(self.pushButton_step, 1, 3, 1, 1)
        self.spinBox_numSteps = QtWidgets.QSpinBox(RunningDialog)
        self.spinBox_numSteps.setMinimum(1)
        self.spinBox_numSteps.setMaximum(1000)
        self.spinBox_numSteps.setSingleStep(10)
        self.spinBox_numSteps.setProperty("value", 1)
        self.spinBox_numSteps.setObjectName("spinBox_numSteps")
        self.gridLayout.addWidget(self.spinBox_numSteps, 1, 4, 1, 1)
        self.pushButton_runToEnd = QtWidgets.QPushButton(RunningDialog)
        self.pushButton_runToEnd.setObjectName("pushButton_runToEnd")
        self.gridLayout.addWidget(self.pushButton_runToEnd, 1, 5, 1, 1)
        self.pushButton_test = QtWidgets.QPushButton(RunningDialog)
        self.pushButton_test.setObjectName("pushButton_test")
        self.gridLayout.addWidget(self.pushButton_test, 1, 6, 1, 1)
        self.pushButton_exit = QtWidgets.QPushButton(RunningDialog)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.gridLayout.addWidget(self.pushButton_exit, 1, 7, 1, 1)
        self.label_scipyTime = QtWidgets.QLabel(RunningDialog)
        self.label_scipyTime.setText("")
        self.label_scipyTime.setObjectName("label_scipyTime")
        self.gridLayout.addWidget(self.label_scipyTime, 2, 0, 1, 1)
        self.pushButton_scipy = QtWidgets.QPushButton(RunningDialog)
        self.pushButton_scipy.setObjectName("pushButton_scipy")
        self.gridLayout.addWidget(self.pushButton_scipy, 3, 0, 1, 1)
        self.pushButton_scikitLearn = QtWidgets.QPushButton(RunningDialog)
        self.pushButton_scikitLearn.setObjectName("pushButton_scikitLearn")
        self.gridLayout.addWidget(self.pushButton_scikitLearn, 3, 1, 1, 1)
        self.label_scikitLearnTime = QtWidgets.QLabel(RunningDialog)
        self.label_scikitLearnTime.setText("")
        self.label_scikitLearnTime.setObjectName("label_scikitLearnTime")
        self.gridLayout.addWidget(self.label_scikitLearnTime, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(RunningDialog)
        QtCore.QMetaObject.connectSlotsByName(RunningDialog)

    def retranslateUi(self, RunningDialog):
        _translate = QtCore.QCoreApplication.translate
        RunningDialog.setWindowTitle(_translate("RunningDialog", "Dialog"))
        self.myQtPlotContainer_left.setToolTip(_translate("RunningDialog", "The current time"))
        self.myQtPlotContainer_left.setWhatsThis(_translate("RunningDialog", "The analog clock widget displays the current time."))
        self.myQtPlotContainer_right.setToolTip(_translate("RunningDialog", "The current time"))
        self.myQtPlotContainer_right.setWhatsThis(_translate("RunningDialog", "The analog clock widget displays the current time."))
        self.pushButton_load.setText(_translate("RunningDialog", "load"))
        self.pushButton_normalize.setText(_translate("RunningDialog", "Normalize"))
        self.pushButton_init.setText(_translate("RunningDialog", "Init"))
        self.pushButton_step.setText(_translate("RunningDialog", "Step"))
        self.pushButton_runToEnd.setText(_translate("RunningDialog", "Run To End"))
        self.pushButton_test.setText(_translate("RunningDialog", "Test"))
        self.pushButton_exit.setText(_translate("RunningDialog", "Exit"))
        self.pushButton_scipy.setText(_translate("RunningDialog", "SciPy"))
        self.pushButton_scikitLearn.setText(_translate("RunningDialog", "SciKit - Learn"))

from MyQtPlotContainer import MyQtPlotContainer
