# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui\Plugins\Widgets\ParametersWidget.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ParametersWidget(object):
    def setupUi(self, ParametersWidget):
        ParametersWidget.setObjectName("ParametersWidget")
        ParametersWidget.resize(571, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ParametersWidget.sizePolicy().hasHeightForWidth())
        ParametersWidget.setSizePolicy(sizePolicy)
        ParametersWidget.setMinimumSize(QtCore.QSize(0, 250))
        ParametersWidget.setMaximumSize(QtCore.QSize(16777215, 250))
        self.verticalLayout = QtWidgets.QVBoxLayout(ParametersWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_header = QtWidgets.QLabel(ParametersWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_header.setFont(font)
        self.label_header.setObjectName("label_header")
        self.horizontalLayout.addWidget(self.label_header)
        self.comboBox_main = QtWidgets.QComboBox(ParametersWidget)
        self.comboBox_main.setObjectName("comboBox_main")
        self.horizontalLayout.addWidget(self.comboBox_main)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea_parameters = QtWidgets.QScrollArea(ParametersWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_parameters.sizePolicy().hasHeightForWidth())
        self.scrollArea_parameters.setSizePolicy(sizePolicy)
        self.scrollArea_parameters.setMaximumSize(QtCore.QSize(700, 300))
        self.scrollArea_parameters.setWidgetResizable(True)
        self.scrollArea_parameters.setObjectName("scrollArea_parameters")
        self.scrollAreaWidgetContents_parameters = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_parameters.setGeometry(QtCore.QRect(0, 0, 551, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_parameters.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_parameters.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_parameters.setMaximumSize(QtCore.QSize(1000, 300))
        self.scrollAreaWidgetContents_parameters.setObjectName("scrollAreaWidgetContents_parameters")
        self.gridLayout_parameters = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_parameters)
        self.gridLayout_parameters.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_parameters.setObjectName("gridLayout_parameters")
        self.label_parameterName = QtWidgets.QLabel(self.scrollAreaWidgetContents_parameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_parameterName.sizePolicy().hasHeightForWidth())
        self.label_parameterName.setSizePolicy(sizePolicy)
        self.label_parameterName.setMinimumSize(QtCore.QSize(0, 30))
        self.label_parameterName.setMaximumSize(QtCore.QSize(10000, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_parameterName.setFont(font)
        self.label_parameterName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_parameterName.setObjectName("label_parameterName")
        self.gridLayout_parameters.addWidget(self.label_parameterName, 1, 0, 1, 1)
        self.label_parameterValue = QtWidgets.QLabel(self.scrollAreaWidgetContents_parameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_parameterValue.sizePolicy().hasHeightForWidth())
        self.label_parameterValue.setSizePolicy(sizePolicy)
        self.label_parameterValue.setMaximumSize(QtCore.QSize(1000, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_parameterValue.setFont(font)
        self.label_parameterValue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_parameterValue.setObjectName("label_parameterValue")
        self.gridLayout_parameters.addWidget(self.label_parameterValue, 1, 1, 1, 1)
        self.scrollArea_parameters.setWidget(self.scrollAreaWidgetContents_parameters)
        self.verticalLayout.addWidget(self.scrollArea_parameters)
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        self.pushButton_reset = QtWidgets.QPushButton(ParametersWidget)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.horizontalLayout_buttons.addWidget(self.pushButton_reset)
        self.pushButton_load = QtWidgets.QPushButton(ParametersWidget)
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout_buttons.addWidget(self.pushButton_load)
        self.pushButton_save = QtWidgets.QPushButton(ParametersWidget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_buttons.addWidget(self.pushButton_save)
        self.label_file = QtWidgets.QLabel(ParametersWidget)
        self.label_file.setObjectName("label_file")
        self.horizontalLayout_buttons.addWidget(self.label_file)
        self.verticalLayout.addLayout(self.horizontalLayout_buttons)

        self.retranslateUi(ParametersWidget)
        QtCore.QMetaObject.connectSlotsByName(ParametersWidget)

    def retranslateUi(self, ParametersWidget):
        _translate = QtCore.QCoreApplication.translate
        ParametersWidget.setWindowTitle(_translate("ParametersWidget", "Form"))
        self.label_header.setText(_translate("ParametersWidget", "Algorithm Parameters"))
        self.label_parameterName.setText(_translate("ParametersWidget", "Parameter Name"))
        self.label_parameterValue.setText(_translate("ParametersWidget", "Parameter Value"))
        self.pushButton_reset.setText(_translate("ParametersWidget", "Reset"))
        self.pushButton_load.setText(_translate("ParametersWidget", "Load"))
        self.pushButton_save.setText(_translate("ParametersWidget", "Save"))
        self.label_file.setText(_translate("ParametersWidget", "File Name"))

