# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui\Chapter 2 - Normalize\AlgorithmDataDesign.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AlgorithmDataDesign(object):
    def setupUi(self, AlgorithmDataDesign):
        AlgorithmDataDesign.setObjectName("AlgorithmDataDesign")
        AlgorithmDataDesign.resize(920, 467)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AlgorithmDataDesign.sizePolicy().hasHeightForWidth())
        AlgorithmDataDesign.setSizePolicy(sizePolicy)
        AlgorithmDataDesign.setMinimumSize(QtCore.QSize(920, 467))
        AlgorithmDataDesign.setStyleSheet("")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(AlgorithmDataDesign)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_normilizeInput = QtWidgets.QLabel(AlgorithmDataDesign)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_normilizeInput.sizePolicy().hasHeightForWidth())
        self.label_normilizeInput.setSizePolicy(sizePolicy)
        self.label_normilizeInput.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_normilizeInput.setFont(font)
        self.label_normilizeInput.setAlignment(QtCore.Qt.AlignCenter)
        self.label_normilizeInput.setObjectName("label_normilizeInput")
        self.verticalLayout_7.addWidget(self.label_normilizeInput)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(AlgorithmDataDesign)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(180, 0))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 180, 334))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 11, 0, 11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_fieldRoll = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_fieldRoll.setFont(font)
        self.label_fieldRoll.setStyleSheet("")
        self.label_fieldRoll.setObjectName("label_fieldRoll")
        self.gridLayout_2.addWidget(self.label_fieldRoll, 2, 0, 1, 1)
        self.label_fieldType = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_fieldType.setFont(font)
        self.label_fieldType.setStyleSheet("")
        self.label_fieldType.setObjectName("label_fieldType")
        self.gridLayout_2.addWidget(self.label_fieldType, 3, 0, 1, 1)
        self.label_normalizeRange = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_normalizeRange.setFont(font)
        self.label_normalizeRange.setStyleSheet("")
        self.label_normalizeRange.setObjectName("label_normalizeRange")
        self.gridLayout_2.addWidget(self.label_normalizeRange, 4, 0, 1, 1)
        self.label_valuesOrder = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_valuesOrder.setFont(font)
        self.label_valuesOrder.setStyleSheet("")
        self.label_valuesOrder.setObjectName("label_valuesOrder")
        self.gridLayout_2.addWidget(self.label_valuesOrder, 6, 0, 1, 1)
        self.label_minRange = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_minRange.setFont(font)
        self.label_minRange.setStyleSheet("")
        self.label_minRange.setObjectName("label_minRange")
        self.gridLayout_2.addWidget(self.label_minRange, 7, 0, 1, 1)
        self.label_normalizeMethod = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_normalizeMethod.setFont(font)
        self.label_normalizeMethod.setStyleSheet("")
        self.label_normalizeMethod.setObjectName("label_normalizeMethod")
        self.gridLayout_2.addWidget(self.label_normalizeMethod, 5, 0, 1, 1)
        self.label_selected = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_selected.sizePolicy().hasHeightForWidth())
        self.label_selected.setSizePolicy(sizePolicy)
        self.label_selected.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_selected.setFont(font)
        self.label_selected.setStyleSheet("")
        self.label_selected.setObjectName("label_selected")
        self.gridLayout_2.addWidget(self.label_selected, 0, 0, 1, 1)
        self.label_name = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("")
        self.label_name.setObjectName("label_name")
        self.gridLayout_2.addWidget(self.label_name, 1, 0, 1, 1)
        self.label_maxRange = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_maxRange.setFont(font)
        self.label_maxRange.setStyleSheet("")
        self.label_maxRange.setObjectName("label_maxRange")
        self.gridLayout_2.addWidget(self.label_maxRange, 8, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.scrollArea_fields = QtWidgets.QScrollArea(AlgorithmDataDesign)
        self.scrollArea_fields.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_fields.setLineWidth(0)
        self.scrollArea_fields.setWidgetResizable(True)
        self.scrollArea_fields.setObjectName("scrollArea_fields")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 709, 355))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_fields = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_fields.setContentsMargins(0, 11, 0, 11)
        self.gridLayout_fields.setObjectName("gridLayout_fields")
        self.scrollArea_fields.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.addWidget(self.scrollArea_fields)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_OK = QtWidgets.QPushButton(AlgorithmDataDesign)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_OK.sizePolicy().hasHeightForWidth())
        self.pushButton_OK.setSizePolicy(sizePolicy)
        self.pushButton_OK.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_OK.setMaximumSize(QtCore.QSize(90, 30))
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.verticalLayout.addWidget(self.pushButton_OK)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_addField = QtWidgets.QPushButton(AlgorithmDataDesign)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_addField.sizePolicy().hasHeightForWidth())
        self.pushButton_addField.setSizePolicy(sizePolicy)
        self.pushButton_addField.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_addField.setMaximumSize(QtCore.QSize(90, 30))
        self.pushButton_addField.setObjectName("pushButton_addField")
        self.verticalLayout_2.addWidget(self.pushButton_addField)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_removeField = QtWidgets.QPushButton(AlgorithmDataDesign)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_removeField.sizePolicy().hasHeightForWidth())
        self.pushButton_removeField.setSizePolicy(sizePolicy)
        self.pushButton_removeField.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_removeField.setMaximumSize(QtCore.QSize(90, 30))
        self.pushButton_removeField.setObjectName("pushButton_removeField")
        self.verticalLayout_3.addWidget(self.pushButton_removeField)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_up = QtWidgets.QPushButton(AlgorithmDataDesign)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_up.sizePolicy().hasHeightForWidth())
        self.pushButton_up.setSizePolicy(sizePolicy)
        self.pushButton_up.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_up.setMaximumSize(QtCore.QSize(90, 30))
        self.pushButton_up.setObjectName("pushButton_up")
        self.verticalLayout_4.addWidget(self.pushButton_up)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_down = QtWidgets.QPushButton(AlgorithmDataDesign)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_down.sizePolicy().hasHeightForWidth())
        self.pushButton_down.setSizePolicy(sizePolicy)
        self.pushButton_down.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_down.setMaximumSize(QtCore.QSize(90, 30))
        self.pushButton_down.setObjectName("pushButton_down")
        self.verticalLayout_5.addWidget(self.pushButton_down)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_Cancel = QtWidgets.QPushButton(AlgorithmDataDesign)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Cancel.sizePolicy().hasHeightForWidth())
        self.pushButton_Cancel.setSizePolicy(sizePolicy)
        self.pushButton_Cancel.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_Cancel.setMaximumSize(QtCore.QSize(90, 30))
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.verticalLayout_6.addWidget(self.pushButton_Cancel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.scrollArea.raise_()
        self.scrollArea_fields.raise_()
        self.scrollArea.raise_()
        self.label_normilizeInput.raise_()

        self.retranslateUi(AlgorithmDataDesign)
        QtCore.QMetaObject.connectSlotsByName(AlgorithmDataDesign)

    def retranslateUi(self, AlgorithmDataDesign):
        _translate = QtCore.QCoreApplication.translate
        AlgorithmDataDesign.setWindowTitle(_translate("AlgorithmDataDesign", "Dialog"))
        self.label_normilizeInput.setText(_translate("AlgorithmDataDesign", "Algorithm Data"))
        self.label_fieldRoll.setText(_translate("AlgorithmDataDesign", "Field Roll"))
        self.label_fieldType.setText(_translate("AlgorithmDataDesign", "Field Type"))
        self.label_normalizeRange.setText(_translate("AlgorithmDataDesign", "Normalize Range"))
        self.label_valuesOrder.setText(_translate("AlgorithmDataDesign", "Values Order"))
        self.label_minRange.setText(_translate("AlgorithmDataDesign", "Min Range"))
        self.label_normalizeMethod.setText(_translate("AlgorithmDataDesign", "Normalize Method"))
        self.label_selected.setText(_translate("AlgorithmDataDesign", "Selected"))
        self.label_name.setText(_translate("AlgorithmDataDesign", "Name"))
        self.label_maxRange.setText(_translate("AlgorithmDataDesign", "Max Range"))
        self.pushButton_OK.setText(_translate("AlgorithmDataDesign", "OK"))
        self.pushButton_addField.setText(_translate("AlgorithmDataDesign", "Add Field"))
        self.pushButton_removeField.setText(_translate("AlgorithmDataDesign", "Remove Field"))
        self.pushButton_up.setText(_translate("AlgorithmDataDesign", "Left"))
        self.pushButton_down.setText(_translate("AlgorithmDataDesign", "Right"))
        self.pushButton_Cancel.setText(_translate("AlgorithmDataDesign", "Cancel"))

